/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/404/': RouteRecordInfo<'/404/', '/404', Record<never, never>, Record<never, never>>,
    '/cesium/': RouteRecordInfo<'/cesium/', '/cesium', Record<never, never>, Record<never, never>>,
    '/cesium/business/BDZWebGLIframe': RouteRecordInfo<'/cesium/business/BDZWebGLIframe', '/cesium/business/BDZWebGLIframe', Record<never, never>, Record<never, never>>,
    '/cesium/business/CardList/': RouteRecordInfo<'/cesium/business/CardList/', '/cesium/business/CardList', Record<never, never>, Record<never, never>>,
    '/cesium/business/CardList/TableContent': RouteRecordInfo<'/cesium/business/CardList/TableContent', '/cesium/business/CardList/TableContent', Record<never, never>, Record<never, never>>,
    '/cesium/business/DDZXWebGLIframe': RouteRecordInfo<'/cesium/business/DDZXWebGLIframe', '/cesium/business/DDZXWebGLIframe', Record<never, never>, Record<never, never>>,
    '/cesium/business/left-card0/': RouteRecordInfo<'/cesium/business/left-card0/', '/cesium/business/left-card0', Record<never, never>, Record<never, never>>,
    '/cesium/business/left-card0/Card1': RouteRecordInfo<'/cesium/business/left-card0/Card1', '/cesium/business/left-card0/Card1', Record<never, never>, Record<never, never>>,
    '/cesium/business/left-card0/Card2': RouteRecordInfo<'/cesium/business/left-card0/Card2', '/cesium/business/left-card0/Card2', Record<never, never>, Record<never, never>>,
    '/cesium/business/left-card0/Card3': RouteRecordInfo<'/cesium/business/left-card0/Card3', '/cesium/business/left-card0/Card3', Record<never, never>, Record<never, never>>,
    '/cesium/business/left-card2/': RouteRecordInfo<'/cesium/business/left-card2/', '/cesium/business/left-card2', Record<never, never>, Record<never, never>>,
    '/cesium/business/LeftCard1': RouteRecordInfo<'/cesium/business/LeftCard1', '/cesium/business/LeftCard1', Record<never, never>, Record<never, never>>,
    '/cesium/business/LeftContainer': RouteRecordInfo<'/cesium/business/LeftContainer', '/cesium/business/LeftContainer', Record<never, never>, Record<never, never>>,
    '/cesium/business/map-label/CesiumLabel1': RouteRecordInfo<'/cesium/business/map-label/CesiumLabel1', '/cesium/business/map-label/CesiumLabel1', Record<never, never>, Record<never, never>>,
    '/cesium/business/map-label/CesiumLabel2': RouteRecordInfo<'/cesium/business/map-label/CesiumLabel2', '/cesium/business/map-label/CesiumLabel2', Record<never, never>, Record<never, never>>,
    '/cesium/business/map-label/CesiumLabel3': RouteRecordInfo<'/cesium/business/map-label/CesiumLabel3', '/cesium/business/map-label/CesiumLabel3', Record<never, never>, Record<never, never>>,
    '/cesium/business/map-label/Charts': RouteRecordInfo<'/cesium/business/map-label/Charts', '/cesium/business/map-label/Charts', Record<never, never>, Record<never, never>>,
    '/cesium/business/map-label/MiniCesiumLabel': RouteRecordInfo<'/cesium/business/map-label/MiniCesiumLabel', '/cesium/business/map-label/MiniCesiumLabel', Record<never, never>, Record<never, never>>,
    '/cesium/business/map-label/RouteCesiumLabelBDZ': RouteRecordInfo<'/cesium/business/map-label/RouteCesiumLabelBDZ', '/cesium/business/map-label/RouteCesiumLabelBDZ', Record<never, never>, Record<never, never>>,
    '/cesium/business/map-label/RouteCesiumLabelBDZNew': RouteRecordInfo<'/cesium/business/map-label/RouteCesiumLabelBDZNew', '/cesium/business/map-label/RouteCesiumLabelBDZNew', Record<never, never>, Record<never, never>>,
    '/cesium/business/map-label/RouteCesiumLabelDDZX': RouteRecordInfo<'/cesium/business/map-label/RouteCesiumLabelDDZX', '/cesium/business/map-label/RouteCesiumLabelDDZX', Record<never, never>, Record<never, never>>,
    '/cesium/business/map-label/RouteCesiumLabelDDZXNew': RouteRecordInfo<'/cesium/business/map-label/RouteCesiumLabelDDZXNew', '/cesium/business/map-label/RouteCesiumLabelDDZXNew', Record<never, never>, Record<never, never>>,
    '/cesium/business/map-label/RouteCesiumLabelFDCNew': RouteRecordInfo<'/cesium/business/map-label/RouteCesiumLabelFDCNew', '/cesium/business/map-label/RouteCesiumLabelFDCNew', Record<never, never>, Record<never, never>>,
    '/cesium/business/map-label/RouteCesiumLabelJSGJ': RouteRecordInfo<'/cesium/business/map-label/RouteCesiumLabelJSGJ', '/cesium/business/map-label/RouteCesiumLabelJSGJ', Record<never, never>, Record<never, never>>,
    '/cesium/business/map-label/RouteCesiumLabelMlKZ': RouteRecordInfo<'/cesium/business/map-label/RouteCesiumLabelMlKZ', '/cesium/business/map-label/RouteCesiumLabelMlKZ', Record<never, never>, Record<never, never>>,
    '/cesium/business/map-label/RouteCesiumLabelRJ': RouteRecordInfo<'/cesium/business/map-label/RouteCesiumLabelRJ', '/cesium/business/map-label/RouteCesiumLabelRJ', Record<never, never>, Record<never, never>>,
    '/cesium/business/map-label/RouteCesiumLabelSJZXNew': RouteRecordInfo<'/cesium/business/map-label/RouteCesiumLabelSJZXNew', '/cesium/business/map-label/RouteCesiumLabelSJZXNew', Record<never, never>, Record<never, never>>,
    '/cesium/business/map-label/RouteCesiumLabelYDGJ': RouteRecordInfo<'/cesium/business/map-label/RouteCesiumLabelYDGJ', '/cesium/business/map-label/RouteCesiumLabelYDGJ', Record<never, never>, Record<never, never>>,
    '/cesium/business/map-label/RouteCesiumLabelZD': RouteRecordInfo<'/cesium/business/map-label/RouteCesiumLabelZD', '/cesium/business/map-label/RouteCesiumLabelZD', Record<never, never>, Record<never, never>>,
    '/cesium/business/right-card0/': RouteRecordInfo<'/cesium/business/right-card0/', '/cesium/business/right-card0', Record<never, never>, Record<never, never>>,
    '/cesium/business/right-card0/Card1': RouteRecordInfo<'/cesium/business/right-card0/Card1', '/cesium/business/right-card0/Card1', Record<never, never>, Record<never, never>>,
    '/cesium/business/right-card0/Card2': RouteRecordInfo<'/cesium/business/right-card0/Card2', '/cesium/business/right-card0/Card2', Record<never, never>, Record<never, never>>,
    '/cesium/business/right-card0/Card3': RouteRecordInfo<'/cesium/business/right-card0/Card3', '/cesium/business/right-card0/Card3', Record<never, never>, Record<never, never>>,
    '/cesium/business/right-card2/': RouteRecordInfo<'/cesium/business/right-card2/', '/cesium/business/right-card2', Record<never, never>, Record<never, never>>,
    '/cesium/business/RightCardBottom0': RouteRecordInfo<'/cesium/business/RightCardBottom0', '/cesium/business/RightCardBottom0', Record<never, never>, Record<never, never>>,
    '/cesium/business/RightCardBottom1': RouteRecordInfo<'/cesium/business/RightCardBottom1', '/cesium/business/RightCardBottom1', Record<never, never>, Record<never, never>>,
    '/cesium/business/RightCardBottom2': RouteRecordInfo<'/cesium/business/RightCardBottom2', '/cesium/business/RightCardBottom2', Record<never, never>, Record<never, never>>,
    '/cesium/business/RightContainer': RouteRecordInfo<'/cesium/business/RightContainer', '/cesium/business/RightContainer', Record<never, never>, Record<never, never>>,
    '/cesium/business/route-planing/': RouteRecordInfo<'/cesium/business/route-planing/', '/cesium/business/route-planing', Record<never, never>, Record<never, never>>,
    '/cesium/business/route-planing/RouteTableContent': RouteRecordInfo<'/cesium/business/route-planing/RouteTableContent', '/cesium/business/route-planing/RouteTableContent', Record<never, never>, Record<never, never>>,
    '/cesium/business/route-planing/TerminalWindow': RouteRecordInfo<'/cesium/business/route-planing/TerminalWindow', '/cesium/business/route-planing/TerminalWindow', Record<never, never>, Record<never, never>>,
    '/cesium/business/route-planing/TextAnimatePanel': RouteRecordInfo<'/cesium/business/route-planing/TextAnimatePanel', '/cesium/business/route-planing/TextAnimatePanel', Record<never, never>, Record<never, never>>,
    '/cesium/business/TopStatus': RouteRecordInfo<'/cesium/business/TopStatus', '/cesium/business/TopStatus', Record<never, never>, Record<never, never>>,
    '/cesium/business/TopTitle': RouteRecordInfo<'/cesium/business/TopTitle', '/cesium/business/TopTitle', Record<never, never>, Record<never, never>>,
    '/cesium/components/CesiumMap': RouteRecordInfo<'/cesium/components/CesiumMap', '/cesium/components/CesiumMap', Record<never, never>, Record<never, never>>,
    '/cesium/components/ol/OpenlayersMap': RouteRecordInfo<'/cesium/components/ol/OpenlayersMap', '/cesium/components/ol/OpenlayersMap', Record<never, never>, Record<never, never>>,
    '/three/': RouteRecordInfo<'/three/', '/three', Record<never, never>, Record<never, never>>,
    '/three/components/ThreeComponent': RouteRecordInfo<'/three/components/ThreeComponent', '/three/components/ThreeComponent', Record<never, never>, Record<never, never>>,
    '/three/pages/building': RouteRecordInfo<'/three/pages/building', '/three/pages/building', Record<never, never>, Record<never, never>>,
    '/three/pages/default': RouteRecordInfo<'/three/pages/default', '/three/pages/default', Record<never, never>, Record<never, never>>,
    '/three/pages/fbx': RouteRecordInfo<'/three/pages/fbx', '/three/pages/fbx', Record<never, never>, Record<never, never>>,
    '/three/pages/gltf': RouteRecordInfo<'/three/pages/gltf', '/three/pages/gltf', Record<never, never>, Record<never, never>>,
  }
}
